### ISSUE TITLE
Failed to fetch standard library grit module

### ISSUE THREAD

**Issue by noahbald** [getgrit/gritql#150]
I'm setting up grit for the first time and trying to test a pattern I've created.
When I run the grit, I get an error
```sh
$ grit apply props_use_swagger

Error: Failed to fetch standard library grit module getgrit/stdlib: Failed to clone repo getgrit/stdlib: authentication required but no callback set; class=Ssh (23); code=Auth (-16)
```

I've also tried logging in through `grit auth` to see if it fixes it, but it hasn't.

Note that I've installed and am using grit with nushell, but I seem to have the same issue when running through zsh.

----
This is the only pattern I have
```grit
// ~/.grit/patterns/<redacted>/common.grit

language js

// Find cases where a member of a prop is imported from swagger types
pattern props_use_swagger() {
  `interface $interface { $entries }` where { and {
    `interface` <: r`Props$`,
    `entries` <: contains `$name: $type` where {
      $type <: ensure_import_from("@/types/swagger")
    }
  } }
}

```

**Comment by morgante** [comment]
Can you share your `~/.git/config`? It looks like something in your system is trying to force git clones to use SSH.

**Comment by noahbald** [comment]
My guess is it's that url/insteadOf business, I'll turn that off for now.
I'll update if that fixes the issue

```toml
[user]
        name = <redacted>
        email = <redacted>
[core]
        editor = nvim
        excludesFile = ~/.gitignore
[url "ssh://git@github.com/"]
        insteadOf = https://github.com/
[rerere]
        enabled = true
        autoUpdate = true
[branch]
        sort = -committerdate
[column]
        ui = auto
[maintenance]
        repo = <redacted>
```
