### ISSUE TITLE
String equivalence in yaml

### ISSUE THREAD

**Issue by morgante** [getgrit/gritql#394]
Two different yaml strings should be treated identically in patterns.

For example, this pattern should match all 3 nodes in the yaml file:

```
language yaml

`'ubuntu-latest'`
```

Sample file:
```
steps:
    - runs_on: "ubuntu-latest"
    - runs_on: 'ubuntu-latest'
    - runs_on: ubuntu-latest

```

It looks like the problem is the underlying AST representations are different in the yaml grammar between single-quote and double-quote strings.
